stages:
  - package

.package-base:
  image: $CI_SERVER_HOST:5050/libretro-infrastructure/libretro-build-amd64-ubuntu:latest
  stage: package
  variables:
    MEDIA_PATH: .media
  script:
    # freej2me: Install ant
    - apt-get update -q -y
    - apt-get install -y ant

    # Build the system files
    - mkdir -p ${MEDIA_PATH}/${CI_PROJECT_NAME}
    - ./make.sh
    - cp out/.index ${MEDIA_PATH}/${CI_PROJECT_NAME}
    - cp out/*.zip ${MEDIA_PATH}/${CI_PROJECT_NAME}
  artifacts:
    paths:
    - ${MEDIA_PATH}
    expire_in: 1 day

libretro-package-any:
  extends: .package-base
